### ISSUE TITLE
refactor and license issues

### ISSUE THREAD

**Issue by maifeeulasad** [maifeeulasad/Joss-Paint#10]

**Comment by smolnp** [comment]
What are the license issues?

**Comment by maifeeulasad** [comment]
@smolnp shouldn't we change the licenses on each file and `Easy Paint` to `Paint` ?
Cause `Gr1n/EasyPaint` is not being supported. That's why thought that I should change the name and details, where Easy Paint is mentioned

**Comment by maifeeulasad** [comment]
https://github.com/maifeeulasad/Paint/commit/78f181d9d54d378049ec922ee9f0137d99733376 , https://github.com/maifeeulasad/Paint/commit/2ca0fda9f9fb102d563d32ebbd3d94f1d2b01d20

**Comment by smolnp** [comment]
Can it be more profitable to use unoccupied names - "OpenPaintQt", "OpenDraw", "EasyDraw", "EasyPencil" or any other? The name "Paint" is quite common and can cause confusion or legal problems.

**Comment by smolnp** [comment]
It is also necessary to mention that the product is an offshoot of EasyPaint and point out the developers of EasyPaint.

**Comment by smolnp** [comment]
Renaming the editor is not long, you just need to choose its name.

**Comment by maifeeulasad** [comment]
@smolnp I've already mentioned there contributions [here](https://github.com/maifeeulasad/Paint/blob/2ca0fda9f9fb102d563d32ebbd3d94f1d2b01d20/README.md#L3-L5), at the very first line of readme. OpenPaint sounds fun. If you are cool with it let me know. We can refactor then.

**Comment by smolnp** [comment]
> OpenPaint

https://openpaint.en.softonic.com/?ex=BB-1549.2, https://github.com/search?q=openpaint

**Comment by maifeeulasad** [comment]
`Joss Drawing` ? I'm quite sure there is no application name joss drawing.

**Comment by smolnp** [comment]
> @smolnp I've already mentioned there contributions [here](https://github.com/maifeeulasad/Paint/blob/2ca0fda9f9fb102d563d32ebbd3d94f1d2b01d20/README.md#L3-L5), at the very first line of readme. OpenPaint sounds fun. If you are cool with it let me know. We can refactor then.

Why isn't Joss Peter? :-))

**Comment by maifeeulasad** [comment]
Let's just keep it `Joss Paint`, and move on.

**Comment by maifeeulasad** [comment]
@smolnp doesn't the license look better now ?

**Comment by maifeeulasad** [comment]
ok, so keep it `Joo Paint` and move forward.

https://github.com/maifeeulasad/Paint/issues/14#issuecomment-747325072
