### ISSUE TITLE
Languages not working

### ISSUE THREAD

**Issue by maifeeulasad** [maifeeulasad/Joss-Paint#14]
not even a single one, maybe due to lines are changed

**Comment by smolnp** [comment]
Languages work when installed natively on the system. The installation commands may differ depending on the installed distribution. But first, you need to completely rename the project. If you settled on "JossPaint" I can rename all the files tonight and provide you with a recipe for installing on Fedora 33, the command may be slightly different for other distributions. My time zone is UTC+02:30:28.

**Comment by maifeeulasad** [comment]
@smolnp yes, go ahead with `JossPaint`

**Comment by smolnp** [comment]
![josspaint](https://user-images.githubusercontent.com/26217756/102514884-1a964c00-409e-11eb-99b5-9adf2a946e99.png)
![josspaint2](https://user-images.githubusercontent.com/26217756/102514894-1cf8a600-409e-11eb-8e42-31ab55097657.png)
cd ./JossPaint/sources
lrelease-qt5 JossPaint.pro
qmake-qt5 && make
sudo make install
